name: arcade_sprite_ext
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pytest=6.2
  - pylint=2.12
  - black=22.3.0
  - pip=22.0.3
  - pydocstyle=6.1.1
  - pip:
    - arcade==2.6.10